# To learn more about these fields
# https://github:com/Layr-Labs/eigenlayer-contracts/blob/master/src/contracts/interfaces/IDelegationManager:sol:
operator:
  address:
  earnings_receiver_address: 
  delegation_approver_address:
  staker_opt_out_window_blocks:
  metadata_url: https://example.com/metadata.json

# EigenLayer Slasher contract address
el_slasher_address: 

# Address of BLS Public Key Compendium contract
bls_public_key_compendium_address:

# ETH RPC URL
eth_rpc_url: http://localhost:8545

# Signer Type to use
# Supported values: local_keystore
signer_type: local_keystore

# Full path to ecdsa private key store file
private_key_store_path: <path-to>/test.ecdsa.key.json

# Full path to bls private key store file
bls_private_key_store_path: <path-to>/test.bls.key.json

# Chain ID: 1 for mainnet, 5 for Goerli, 31337 for local
chain_id: 5